// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBESrnrgUdttmWjpS9pGKCkNUKGLVcSDw',
    appId: '1:812989379162:web:efd57ab18dae0f048b1e63',
    messagingSenderId: '812989379162',
    projectId: 'bookmyslot-8342f',
    authDomain: 'bookmyslot-8342f.firebaseapp.com',
    storageBucket: 'bookmyslot-8342f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPnHd8HgvObSE1kyk2LKyhFBhhFPOTkK0',
    appId: '1:812989379162:android:8dc579bef8b78ace8b1e63',
    messagingSenderId: '812989379162',
    projectId: 'bookmyslot-8342f',
    storageBucket: 'bookmyslot-8342f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD74SuId9m2RKgr0u2MQfrbUI5Noc_kyNk',
    appId: '1:812989379162:ios:9efcce00198550d78b1e63',
    messagingSenderId: '812989379162',
    projectId: 'bookmyslot-8342f',
    storageBucket: 'bookmyslot-8342f.firebasestorage.app',
    iosBundleId: 'com.example.bookmyslot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD74SuId9m2RKgr0u2MQfrbUI5Noc_kyNk',
    appId: '1:812989379162:ios:9efcce00198550d78b1e63',
    messagingSenderId: '812989379162',
    projectId: 'bookmyslot-8342f',
    storageBucket: 'bookmyslot-8342f.firebasestorage.app',
    iosBundleId: 'com.example.bookmyslot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBESrnrgUdttmWjpS9pGKCkNUKGLVcSDw',
    appId: '1:812989379162:web:66a95dcd7531f8608b1e63',
    messagingSenderId: '812989379162',
    projectId: 'bookmyslot-8342f',
    authDomain: 'bookmyslot-8342f.firebaseapp.com',
    storageBucket: 'bookmyslot-8342f.firebasestorage.app',
  );
}
